version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1.26-r2'
    environment:
      # MARIADB_USER:
      # MARIADB_PASSWORD:
      MARIADB_HOST:
      MARIADB_PORT_NUMBER:
      # MARIADB_ROOT_PASSWORD:
      ALLOW_EMPTY_PASSWORD:
    volumes:
      - '/srv/docker/testlink/mariadb:/bitnami'

  testlink:
    image: 'bitnami/testlink:1.9.16-r8'
    # labels:
      # kubernetes integration
      # kompose.service.type: nodeport
    environment:
      TESTLINK_USERNAME:
      TESTLINK_PASSWORD:
      TESTLINK_EMAIL:
      TESTLINK_LANGUAGE:

      SMTP_ENABLE:
      SMTP_HOST:
      SMTP_PORT:
      SMTP_USER:
      SMTP_PASSWORD:
      SMTP_CONNECTION_MODE:
    # ports:
    #   - '80:80'
    #   - '443:443'
    # volumes:
    #   - 'testlink_data:/bitnami'

    labels:
      io.rancher.sidekicks: testlink-data
    volumes_from:
      - testlink-data
    links:
      - mariadb

  testlink-data:
    image: library/busybox:latest
    labels:
      io.rancher.container.start_once: true
    entrypoint:
      - "/bin/true" # el comando devuelve verdadero (succefully)
    volumes:
      - "/srv/docker/testlink/testlink:/bitnami"

# volumes:
#   mariadb_data:
#     driver: local
#   testlink_data:
#     driver: local
